sudo: required
services:
  - docker

before_install:
  - docker build -t mehdignu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehdignu/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: encounter-react
  on:
    repo: mehdignu/docker-react